/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/canchas/[id]` | `/canchas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservas/[id]` | `/reservas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/canchas` | `/canchas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservas` | `/reservas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/canchas/[id]` | `/canchas/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/reservas/[id]` | `/reservas/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/canchas/[id]` | `/canchas/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reservas/[id]` | `/reservas/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/canchas` | `/canchas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reservas` | `/reservas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/canchas/[id]` | `/canchas/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/reservas/[id]` | `/reservas/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/canchas/[id]${`?${string}` | `#${string}` | ''}` | `/canchas/[id]${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reservas/[id]${`?${string}` | `#${string}` | ''}` | `/reservas/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/canchas${`?${string}` | `#${string}` | ''}` | `/canchas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reservas${`?${string}` | `#${string}` | ''}` | `/reservas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/canchas/[id]` | `/canchas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservas/[id]` | `/reservas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/canchas` | `/canchas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservas` | `/reservas`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/canchas/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/canchas/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reservas/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/reservas/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/canchas/[id]` | `/canchas/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/reservas/[id]` | `/reservas/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
