spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/reserva_canchas
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=0123456789abcdef0123456789abcdef
jwt.expiration=3600000
